name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-11-jdk python3-pip autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libtinfo5 cmake libffi-dev libssl-dev
        
    - name: Install Buildozer and dependencies
      run: |
        pip install buildozer
        pip install -r requirements.txt
        
    - name: Run Buildozer
      run: |
        buildozer init
        # Update buildozer.spec with necessary changes
        sed -i 's/^requirements = .*/requirements = python3,kivy,ecdsa,base58,bech32,mnemonic,requests,colorama/' buildozer.spec
        sed -i 's/^android.accept_sdk_license = .*/android.accept_sdk_license = True/' buildozer.spec
        buildozer -v android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: btc-wallet-generator
        path: bin/*.apk
